a=int(input("Enter the number : "))
b=int(input("Enter the number : "))

print("Addition of a and b ",a+b)
print("Subtraction of a and b",a-b)
print("Multiplication of a and b",a*b)
print("Division of a and b",a/b)
print("Modulus of a and b",a%b)
print("Floor Division of a and b",a//b)
print("power function of a and b",a**b)
